### ISSUE TITLE
[FEEDBACK] Konstantinos' Beta Test Feedback

### ISSUE THREAD

**Issue by KonstantinosD** [algosup/2024-2025-project-2-serious-game-team-8#36]
### Tester Name

Konstantinos

### Educational Impact

Actually, yes! I did learn about the evolution in solar panels.

### Engagement Level

Moderately engaging

### Favorite Part

Loved unlocking new cards, and how they created a sense of real space packed with physical elements. Slightly more challenging puzzles (which, I am certain will soon be added) would have made things more interesting/fun, but you've got a great foundation for a game already.

### Least Favorite Part

The UI of the app needs to be improved, and it should be used to explain things more clearly to players.

### Bugs or Issues

Nothing 

### Difficulty Balance

Too easy

### App-Card Integration

Entering the codes was not obvious

### Usability Feedback

The function of every element of the app's UI should be more obvious. Also, in the introductory game cards actually have the cards and the app act as tutorials. For example, have a card telling me to add its number to that of another card.

### Accessibility Rating

Average

**Comment by mathiskakal** [comment]
Thank you for your Feedback !
