### ISSUE TITLE
[DOCS] User Manual Missing Legal Mentions

### ISSUE THREAD

**Issue by mathiskakal** [algosup/2024-2025-project-2-serious-game-team-8#67]
> IMPROVEMENT: Missing Legal Mentions

 - [x] 1. Limited License

Explain the license granted to the user, typically for personal and non-commercial use. Example:
“This game and app are licensed, not sold, to you. You are granted a non-exclusive, non-transferable license to use the product solely for personal entertainment purposes.”

 - [x] 2. Disclaimer of Liability

Disclaim responsibility for potential issues such as data loss, errors, or damages caused by the app. Example:
“[Your Company] is not liable for any damages arising from the use or inability to use this product, including but not limited to loss of data or disruptions in gameplay.”

 - [ ] 3. End-User License Agreement (EULA)

Refer to or summarize the terms of the EULA if applicable. Example:
“By using this product, you agree to abide by the terms of the End-User License Agreement included with the app or available online at [website link].”

 - [ ] 4. Online Connectivity and Data Usage

If the app requires an internet connection or collects user data, disclose this in compliance with data protection laws (e.g., GDPR, CCPA). Example:
“This app requires an internet connection to access certain features. By using the app, you consent to the collection and use of data as outlined in our Privacy Policy, available at [website link].”

 - [ ] 5. Third-Party Components and Licenses

Acknowledge any third-party tools, libraries, or assets used in the app or card game. Example:
“This product uses third-party software licensed under their respective terms. Full details can be found in the app’s credits or on our website.”

 - [ ] 6. Contact Information

Provide a way for users to reach the company for support or legal inquiries. Example:
“For support or legal questions, contact us at [email address] or visit [website link].”

**Comment by TechXplorerFR** [comment]
Limited License has been applied to the document ✅

**Comment by TechXplorerFR** [comment]
Disclaimer of Liability has been added to the user manual ✅

**Comment by TechXplorerFR** [comment]
Other information seems unrelevant to add for now, it will be added in future version as they would require another document formatting.

**Comment by mathiskakal** [comment]
Great job in the limited time nonetheless!
